version: '3.9'
services:
  linuxgsm:
    image: "jager1888/codeserver:latest"
    container_name: code-server
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Budapest
      - PASSWORD=****
      - SUDO_PASSWORD=****
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - /home/ubuntu/codeserver/workspace:/config
    ports:
      - "8443:8443"
      - "3000:3000"
    restart: unless-stopped
